/*
 * generated by Xtext
 */
package org.shashwat.xtext.latexQ.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LatexQUiModule extends org.shashwat.xtext.latexQ.ui.AbstractLatexQUiModule {
	public LatexQUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
