/*
 * generated by Xtext
 */
package org.shashwat.xtext.latexQ;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LatexQUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.shashwat.xtext.latexQ.ui.internal.LatexQActivator.getInstance().getInjector("org.shashwat.xtext.latexQ.LatexQ");
	}
	
}
