/*
 * generated by Xtext
 */
package org.shashwat.xtext.latexQ.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractLatexQValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.shashwat.xtext.latexQ.latexQ.LatexQPackage.eINSTANCE);
		return result;
	}
}
