/**
 * generated by Xtext
 */
package org.shashwat.xtext.latexQ.validation;

import org.shashwat.xtext.latexQ.validation.AbstractLatexQValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LatexQValidator extends AbstractLatexQValidator {
}
