/**
 * generated by Xtext
 */
package org.shashwat.xtext.latexQ.ui.contentassist;

import org.shashwat.xtext.latexQ.ui.contentassist.AbstractLatexQProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LatexQProposalProvider extends AbstractLatexQProposalProvider {
}
