/*
 * generated by Xtext
 */
package org.shashwat.xtext.latexQ.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.shashwat.xtext.latexQ.services.LatexQGrammarAccess;

public class LatexQParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LatexQGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.shashwat.xtext.latexQ.parser.antlr.internal.InternalLatexQParser createParser(XtextTokenStream stream) {
		return new org.shashwat.xtext.latexQ.parser.antlr.internal.InternalLatexQParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "QuestionPaper";
	}
	
	public LatexQGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LatexQGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
