/*
 * generated by Xtext
 */
package org.shashwat.xtext.latexQ;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LatexQRuntimeModule extends org.shashwat.xtext.latexQ.AbstractLatexQRuntimeModule {

}
