/*
 * generated by Xtext
 */
package org.shashwat.xtext.latexQ;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LatexQStandaloneSetup extends LatexQStandaloneSetupGenerated{

	public static void doSetup() {
		new LatexQStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

